# Generated by Django 4.2.16 on 2025-02-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuurlmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='menuurlpermissiondetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='menuurlpermissionmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modulemaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rolemaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usermaster',
            options={'managed': False},
        ),
    ]
