# Generated by Django 4.2.16 on 2025-02-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FootwearImage',
        ),
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='footwear',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='footwearcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='footwearvariant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gstmaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='return',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True},
        ),
    ]
